# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa69cefef84b3f10f7cda5a304c81fcb57fb254e31783bf5644bd80fca690817538a9814831eae378f89c9e19ac517d3e409e8bfafb8fa24c55412a850a7ad7c

test:
  secret_key_base: 8f9e49405f80a37a890ab0447d893b7d007fbeeded66db588fa1f2c711b53d359f1dddcaa9a4b29728d15e1187e5ba9f5a51b9bb86b82dfc59d9c7fcdbbc1878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
